export const colorKeyConstants = {
  NEW_COLOR: 'NEW_COLOR',
  EDIT_COLOR: 'EDIT_COLOR',
  ADD_BULK_COLOR: 'ADD_BULK_COLOR',
  ADD_CODE_COLOR: 'ADD_CODE_COLOR',
  CLEAR_COLOR_LIST: 'CLEAR_COLOR_LIST',
  CLEAR_COLOR_ITEM: 'CLEAR_COLOR_ITEM',
}